// <auto-generated />
using ArwynFr.Reforger.ModpackMgr.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArwynFr.Reforger.ModpackMgr.Database.Migrations
{
    [DbContext(typeof(ModsDbContext))]
    [Migration("20260531141623_Mods")]
    partial class Mods
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ArwynFr.Reforger.ModpackMgr.Domain.Mod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("ArwynFr.Reforger.ModpackMgr.Domain.Mod", b =>
                {
                    b.OwnsOne("ArwynFr.Reforger.ModpackMgr.Domain.WorkshopInformation", "WorkshopInformation", b1 =>
                        {
                            b1.Property<string>("ModId")
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("Dependencies")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("GameVersion")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ModId");

                            b1.ToTable("Mods");

                            b1.WithOwner()
                                .HasForeignKey("ModId");
                        });

                    b.Navigation("WorkshopInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
