// <auto-generated />
using ArwynFr.Reforger.ModpackMgr.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArwynFr.Reforger.ModpackMgr.Database.Migrations
{
    [DbContext(typeof(ModsDbContext))]
    partial class ModsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ArwynFr.Reforger.ModpackMgr.Domain.Mod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("ModMod", b =>
                {
                    b.Property<string>("DependantsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependenciesId")
                        .HasColumnType("TEXT");

                    b.HasKey("DependantsId", "DependenciesId");

                    b.HasIndex("DependenciesId");

                    b.ToTable("ModMod");
                });

            modelBuilder.Entity("ArwynFr.Reforger.ModpackMgr.Domain.Mod", b =>
                {
                    b.OwnsOne("ArwynFr.Reforger.ModpackMgr.Domain.WorkshopInformation", "WorkshopInformation", b1 =>
                        {
                            b1.Property<string>("ModId")
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("Dependencies")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("GameVersion")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<long?>("Size")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ModId");

                            b1.ToTable("Mods");

                            b1.WithOwner()
                                .HasForeignKey("ModId");
                        });

                    b.Navigation("WorkshopInformation");
                });

            modelBuilder.Entity("ModMod", b =>
                {
                    b.HasOne("ArwynFr.Reforger.ModpackMgr.Domain.Mod", null)
                        .WithMany()
                        .HasForeignKey("DependantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArwynFr.Reforger.ModpackMgr.Domain.Mod", null)
                        .WithMany()
                        .HasForeignKey("DependenciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
